[package]
name = "authsome-client-example"
version = "1.0.0"
edition = "2021"

[dependencies]
authsome-client = { path = "../../../clients/generated/rust" }
tokio = { version = "1.0", features = ["full"] }

